name: CI

on:
  pull_request:

  push:
    branches: [main]

env:
  GIT_COMMIT_SHA: ${{ github.sha }}
  GIT_BRANCH: ${{ github.ref }}

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  linting:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITH: lint
      BUNDLE_WITHOUT: development:test

    steps:
      - uses: actions/checkout@v6

      - name: Setup Ruby 3.x
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3
          bundler-cache: true

      - name: Rubocop
        run: bundle exec rubocop --format progress

  build:
    needs: [linting]
    runs-on: ubuntu-latest
    name: build ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.2", "3.3", "3.4", "4.0"]
        experimental: [false]
        include:
          - ruby: head
            experimental: true

    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: RSpec
        continue-on-error: ${{ matrix.experimental }}
        run: bundle exec rspec
